### PR TITLE
Disable serde_json recursion limit for IPC deserialization

### LINKED ISSUE #71: serde_json recursion limit exceeded when deserializing events with deep node trees
When the sway tree has enough nested containers (e.g. 15+ windows across multiple workspaces with tabbed/stacked layouts), event deserialization fails with:  `recursion limit exceeded at line 1 column 31070`

This happens because Event::decode in types/src/error/event.rs uses serde_json::from_slice with the default recursion limit of 128. Sway's Node struct is recursive (nodes: Vec<Node>, floating_nodes: Vec<Node>), and deep trees exceed this limit.

The same issue likely affects Connection::get_tree() and other reply deserialization in blocking/src/common.rs.

Suggested fix:

Replace serde_json::from_slice(&payload)? with a deserializer that has a higher (or disabled) recursion limit:
```rust
  let mut deserializer = serde_json::Deserializer::from_slice(&payload);
  deserializer.disable_recursion_limit();
  let event = serde::Deserialize::deserialize(&mut deserializer)?;
```
Environment:
  - sway 1.11
  - swayipc 4.0
  - Triggered with ~30-37KB JSON payloads, depth unknown but within normal desktop usage

### PR DESCRIPTION
**Pull request by htimur**
Fixes https://github.com/JayceFayne/swayipc-rs/issues/71

## Summary

- Enable serde_json's `unbounded_depth` feature and call `disable_recursion_limit()` on all deserialization paths
- Fixes `recursion limit exceeded` errors when sway's node tree exceeds 128 levels of JSON nesting
- Affects both `Event::decode` (event stream) and `CommandType::decode` (command replies like `get_tree`)

## Problem

Sway's `Node` struct is recursive (`nodes` and `floating_nodes` contain `Vec<Node>`). With enough nested containers (e.g. 15+ windows across multiple workspaces with tabbed/stacked layouts), the IPC JSON payloads exceed serde_json's default recursion limit of 128, causing deserialization failures.

This manifests as intermittent errors in downstream consumers like [swayr](https://git.sr.ht/~tsdh/swayr):
```
Error while receiving events: recursion limit exceeded at line 1 column 31070
```

## Approach

`serde_json` only offers two options: the default limit of 128, or fully unbounded (via the `unbounded_depth` feature). There is no API to set a custom limit. Since sway IPC is a local Unix socket with trusted input, and tree depth is naturally bounded by the compositor's window management, disabling the limit is safe.

### CODE REVIEW

File: types/src/error/event.rs [hunk 1]
```diff
@@ -3,23 +3,30 @@ use crate::{
     Event::{self, *},
     Fallible,
 };
+use serde::Deserialize;
+
+fn deserialize_from_slice<'a, T: Deserialize<'a>>(payload: &'a [u8]) -> serde_json::Result<T> {
```
Comment (JayceFayne) [inline types/src/error/event.rs]: Pls move this to [utils](https://github.com/JayceFayne/swayipc-rs/blob/master/types/src/utils/serde.rs)

File: types/src/error/command_type.rs [hunk 2]
```diff
@@ -7,6 +7,8 @@ impl CommandType {
         if payload_type != command_type {
             return Err(InvalidCommandType(payload_type, command_type));
         }
-        Ok(serde_json::from_slice(&payload)?)
```
Comment (JayceFayne) [inline types/src/error/command_type.rs:10]: Can reuse the utility function here

**Review by JayceFayne — CHANGES_REQUESTED** [review]
Good catch! In general this approach lgtm

**Comment by htimur** [comment]
@JayceFayne thanks for the quick review.  Moved `deserialize_from_slice` to `utils/serde.rs` and updated both `event.rs` and `command_type.rs` to use it.

**Comment by JayceFayne** [comment]
Thanks for working in this!
